sudo: true

services:
  - docker

language: node_js

env:
  global:
      - secure: "IaFu5mxFwvCYh2/phr416ScFUx80BHmdP4bnniAR1BKHvmW4duLem9GBBu265Qvd6zHD9hEHaq526BNLLhCW/aQUc3EqzawotV5rLnbXX8Qv3RwmPZQznr5JzvzhPuf+rUOObF7j/A6wYLHE+NsreLQs/JTBO/YtKMWLW1VLAuRXeeKBdLyhyMgm5vv8j8QrP0JtEM4L/K9B5CuRIRAh/BKEewOfyn3yWxQWVsEMlSs1f3S1Aah90qjg5MxWG3F0Doqhp1u8hX+LuFmo8npC9h9wa99Fdat1MnbOo7tQZ+xWIo1EzXZodQNTAp6S62cJRw0T9/KbCdgXUz9ug2kTOfh9zFSKkws1p9/H0auPKiczb3Ue1/2G8ksC8wWPR7HLncZSB0G5Re5Y02w10+Bw4jk1iV7vQB04m5asWjP+sONFhRAZ3KlF8yBQom47pf6DrKMadmU2vmDOpM9K+irP45yCJm0HbX9eEC/pXr0PM3JU8cFyEUcA6Fzap9mtrQRDOdjtQxap7qz+PGUSl7E1JWApwklfKI4wEBMLaAMMYgmODWSxhPV22gfXDXoG3Z1htnJNUyj4tBxu0A+8Or793J1gzwLDD07PhZqzIbDgGe5Nit6cGnI4FuPXyWz2bGrynO+oCgYkWCFkemLbLyHvSMDVl9VdFW6pCsoxK12VN/w=" 
      - secure: "Hr1VA8Ptru5ICoBEVzzlNvixNnMfr9LFWM34zbgWFEHHYFcAGRlDgimbq2vzRLiDbCofrmSA5wREz9U477aH9fvScgJoJpBNRkh0cknw3YmsJgpYP1xrB7FGKb6v7de9T00SMJ28eW27NT2puqG/iMP9f3HcJ8NLofrbgPn51YUG9kdsppPdkUBJKelDTEOG5rEBw1LW1HoaarA+nsJDwTAh9kQmtodT97D5anE28jn5XmQxoWF871z9YM637pdz3tTrAl/4mMLFLMQp157HO0+rxvmJWkyzepmb0t+14IOO46vhwqKFDGtvHN0iPTeRqH83WVIYaEdF3WEOsdyf1d2lc6CfU1K6H7VOuNJJrnis1cAP83/uAglDfoN7/B0Ioj+LC3eGXoUStRIBvLnNs9et+TI/fYncHZ6K/5uyiwadA3wyOHvLtyi4977cSyNWZ8TEO1Rqz0d78Ir75G11JnpWeqHB2vVmnZuLMHQLAoF+FyKRbUdZhMFLgpb9TLCpoa0aHBxHT3ElsQIQJ8WGGiU9tXPZWj/taBYtq3YDnoN0pnKEjfYtayQdKhUzKoGy7IZekbVVO9rebWcL2RtZ4RJbyLR12sA5KcbfzSm0Osz34IEqTlaUMOpVnQlNWkaHtYXLAlQUHUbckLBbgq2Fg68g4/PFDMuu2lkSr6pQn48="
      
node_js:
  - 11

install:
  - yarn

script:
  - echo "$REGISTRY_USER"
  - curl -L https://github.com/kubernetes/kompose/releases/download/v1.17.0/kompose-linux-amd64 -o kompose
  - chmod +x kompose
  - sudo mv ./kompose /usr/local/bin/kompose
  - docker login -u=$REGISTRY_USER -p=$REGISTRY_PASS
  - cd build
  - kompose up
  - yarn test:coveralls server/build/js/app.test.js
    
notifications:
  email: false