sudo: true

services:
  - docker

language: node_js

env:
  global:
    - REGISTRY_USER : 
        secure: "lurKyAU7P+T5ATFapaBaMPHPi1T+9AIzqBnmyPMb8z/RG3PcIDdXKuSaEnwnniPFBrrQowUoblfowxYL8U1bUUW6RgIIu/oqYwwzuQctu7jHPeKGTYUQPjHPXXBt6kqUcUASxyvUjcGQhSWwMXd7OIbZaZ396ILOLQu/ajRaDI0K8qfsXWnGPT3LMWtHG73ji0wjRNjbSHpk3rYSSFVtV2DI/oPd8bBKL4lX6wc6/2icekcPk+Ao9PIYmoV4tOYRBXBbaAUAuOqlHtlrQXXkcDbDAmS05Ma87XttK0py4EwTdmxwgCocU1oGi6L+Bh8Ak9cHVtgNsRryKG3Qxto4bZzrwM9EBdMhQkBQFOMo86ybxs71unxsWnBQdIcQK3kU9U3b9Af5+MP5HL4/QasTYnwHYJGKzJ1z/kgMc7PGRDMNRrwDjXeKEE2BeQqnvyB5GXOmQXD8xg/03tfhB5NA2Yd+DIHVDPims95SQtxt54o8fIa3npD4s+uvEO3U//bLg1x0jmSfy7Phd4Na0gR+APCDDRyeZDTVOCsMI6j54nA4bf+aaZFr1NJ4eEnQk3QdkIAX1irt2/Jc9Q53qeijwk2OZ0FvC8JthFcK9cPnhv+6BGd/qfzPzOTzmjaSA/YFypLBXeDSeTCeV3Comndy8l56iv5X7R+D3CeQOF6aSMg="
    - REGISTRY_PASS : 
        secure: "WzrSFeKGGNaQjDYszf18xS6brpONOasYFJ1oHE62lb4WscatGFhKtBBt97Ip5+BICUOMDdrPVPJJ3LoKHG/rymf0HLrjtFuze2HvJBIbPmgSpb8tvcTuOXMiYEwmNjlMR3nS5QYL93MKxz5bgZW/IDL86ivhGCeAQ8qOZSwGskyJ75DDVQVc+rJYNRLq+UYBg+UQPXb9TP+kO6oNxirTk3lCtPU186/GwGviinHEUU0Me/XxTH8dqTEKnwQQHiVLPh989k5Gytz5bq5u5rxFHCXlq++iIF0HoIUOCC9F/K3ilHizisRJNnEVUHForl7QGXwTvpqMzKS9R8AyCg0PZGOhaWUXOYfxMqeQRZTv/9DGlCjndnT8HA+wx0FDXeFKDZMs1ExwZ7Tlspd+IyxxBCMdtWBeZauEzBIrpxJEMvFVfetBp0a0/wS6uCVbnmhgcxjGYELokFUhi7Kl/0ebmbPSuNsCWb5Rk9Cmq043ca0d1JHfoGuVXWc84jIhlbLdCzbb7h0wFTYSyjMsAgIidy93JrolX+a2BuQdsf+/zq2Yt2vfksDNLzEJJXFsxQC/Jr0YgHUdP9LHlXgRsUsHjI35+DCompqitRrUsAz7X9dO5Mtra1k+3qlTyVEJ/2VFjiK/o68RnAkGXyPh75efBA0y5GgN5nnImJkR6fmbjb8="

node_js:
  - 11

install:
  - yarn

script:
  - echo "$REGISTRY_USER"
  - curl -L https://github.com/kubernetes/kompose/releases/download/v1.17.0/kompose-linux-amd64 -o kompose
  - chmod +x kompose
  - sudo mv ./kompose /usr/local/bin/kompose
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASS
  - cd build
  - kompose up
  - yarn test:coveralls server/build/js/app.test.js
    
notifications:
  email: false